---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: intoto-webhook
  labels:
    app: intoto-webhook
  namespace: in-toto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: intoto-webhook
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: intoto-webhook
          image: controlplane/in-toto-webhook:0.1-dev
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          command:
            - ./in-toto
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-key-file=/etc/webhook/certs/key.pem
            - -min-score=0
          ports:
            - containerPort: 8080
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8081
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8081
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
            requests:
              memory: "32Mi"
              cpu: "10m"
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: in-toto-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: intoto-webhook
  labels:
    app: intoto-webhook
  namespace: in-toto
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: intoto-webhook
